# block height, last block processed, and amount of blocks that have numbers were processed
PREFIX b: <https://mobr.ai/ont/blockchain#>
PREFIX c: <https://mobr.ai/ont/cardano#>

SELECT ?currentCardanoHeight (MAX(?blockNum) AS ?capBlockNum) (COUNT(?block) AS ?count)
WHERE {
  c:Cardano b:hasCurrentBlockHeight ?currentCardanoHeight .
  ?block a b:Block .
  ?block c:hasBlockNumber ?blockNum .
}
GROUP BY (?currentCardanoHeight)