# How many transactions in the last 24h?
PREFIX blockchain: <https://mobr.ai/ont/blockchain#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (COUNT(?tx) AS ?count)
WHERE {
    ?block a blockchain:Block ;
        blockchain:hasTx ?tx ;
        blockchain:hasTimestamp ?timestamp .

    BIND (NOW() - "P1D"^^xsd:dayTimeDuration as ?oneDayAgo)
    FILTER (?timestamp >= ?oneDayAgo)
}