"""add cardano auth challenge table

Revision ID: 1a4dda3a21c3
Revises: a5fcb5200cff
Create Date: 2026-05-18 14:52:13.185626

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a4dda3a21c3'
down_revision: str | Sequence[str] | None = 'a5fcb5200cff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardano_auth_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(length=64), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('wallet_name', sa.String(length=64), nullable=True),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_hex', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cardano_auth_challenge_expires_status', 'cardano_auth_challenge', ['expires_at', 'status'], unique=False)
    op.create_index('idx_cardano_auth_challenge_wallet_status', 'cardano_auth_challenge', ['wallet_address', 'status'], unique=False)
    op.create_index(op.f('ix_cardano_auth_challenge_challenge_id'), 'cardano_auth_challenge', ['challenge_id'], unique=True)
    op.create_index(op.f('ix_cardano_auth_challenge_created_at'), 'cardano_auth_challenge', ['created_at'], unique=False)
    op.create_index(op.f('ix_cardano_auth_challenge_expires_at'), 'cardano_auth_challenge', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cardano_auth_challenge_nonce'), 'cardano_auth_challenge', ['nonce'], unique=True)
    op.create_index(op.f('ix_cardano_auth_challenge_wallet_address'), 'cardano_auth_challenge', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cardano_auth_challenge_wallet_address'), table_name='cardano_auth_challenge')
    op.drop_index(op.f('ix_cardano_auth_challenge_nonce'), table_name='cardano_auth_challenge')
    op.drop_index(op.f('ix_cardano_auth_challenge_expires_at'), table_name='cardano_auth_challenge')
    op.drop_index(op.f('ix_cardano_auth_challenge_created_at'), table_name='cardano_auth_challenge')
    op.drop_index(op.f('ix_cardano_auth_challenge_challenge_id'), table_name='cardano_auth_challenge')
    op.drop_index('idx_cardano_auth_challenge_wallet_status', table_name='cardano_auth_challenge')
    op.drop_index('idx_cardano_auth_challenge_expires_status', table_name='cardano_auth_challenge')
    op.drop_table('cardano_auth_challenge')
    # ### end Alembic commands ###
